version: '3.4'

services:
  peoplemanagement:
    image: ${DOCKER_REGISTRY-}peoplemanagement
    build:
      context: .
      dockerfile: PeopleManagement/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "My_password123"
      ACCEPT_EULA: "Y"
